"""
tools/generate_enemies.py
─────────────────────────
Converts data/enemy_locations.csv → extracted_enemy_locations.py

Run whenever enemy_locations.csv changes:
    python tools/generate_enemies.py

Never edit extracted_enemy_locations.py by hand.

CSV columns (must match exactly):
    level_id, source_file, offset, object, category,
    save_idx, is_tracked, is_verified, zone, x, y, z,
    notes, context_group, movement_type
"""

import csv
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))  # project root
sys.path.insert(0, str(Path(__file__).parent))          # tools/ — for sibling imports

from generate import parse_gate_expr

ROOT     = Path(__file__).parent.parent
CSV_PATH = ROOT / "data" / "enemy_locations.csv"
OUT_PATH = ROOT / "extracted_enemy_locations.py"

REQUIRED_COLUMNS = {
    "level_id", "source_file", "offset", "object", "category",
    "save_idx", "is_tracked", "is_verified", "zone", "x", "y", "z",
    "notes", "context_group", "movement_type", "level_region", "sub_region",
}

VALID_CATEGORIES     = {"enemy", "enemy_locked", "ambient", "ambient_locked", "boss", "boss_locked"}
VALID_SOURCE_FILES   = {"enemies.rsc", "enemys.rsc", "objects.rsc", "resource.rsc", "events.rsc", "instance.rsc", "day.rsc", "night.rsc", "fx.rsc"}
VALID_CONTEXT_GROUPS = {"deadside", "deadside_interior", "liveside","liveside_day","liveside_night","liveside_night_interior", "asylum", "any", ""}
VALID_MOVEMENT_TYPES = {"ground", "flying", "swimming", ""}


def parse_offset(raw: str) -> int:
    raw = raw.strip()
    return int(raw, 16) if raw.startswith(("0x", "0X")) else int(raw)


def validate(rows: list[dict]) -> list[str]:
    errors = []
    seen = set()
    for i, row in enumerate(rows, 2):
        lid = row["level_id"].strip()
        sf  = row["source_file"].strip()
        cat = row["category"].strip()
        cg  = row["context_group"].strip()
        mt  = row["movement_type"].strip()
        try:
            off = parse_offset(row["offset"])
        except ValueError:
            errors.append(f"Row {i}: bad offset '{row['offset']}'")
            continue
        key = f"{lid}:{sf}:0x{off:04X}"
        if key in seen:
            errors.append(f"Row {i}: duplicate {key}")
        seen.add(key)
        if cat and cat not in VALID_CATEGORIES:
            errors.append(f"Row {i} ({key}): bad category '{cat}'")
        if sf not in VALID_SOURCE_FILES:
            errors.append(f"Row {i} ({key}): bad source_file '{sf}'")
        if cg not in VALID_CONTEXT_GROUPS:
            errors.append(f"Row {i} ({key}): bad context_group '{cg}'")
        if mt not in VALID_MOVEMENT_TYPES:
            errors.append(f"Row {i} ({key}): bad movement_type '{mt}'")
        if cat == "enemy" and not cg:
            errors.append(f"Row {i} ({key}): category=enemy but context_group is empty")
        if cat == "enemy" and not mt:
            errors.append(f"Row {i} ({key}): category=enemy but movement_type is empty")
        if cat == "ambient" and not cg:
            errors.append(f"Row {i} ({key}): category=ambient but context_group is empty")
        if cat == "ambient" and not mt:
            errors.append(f"Row {i} ({key}): category=ambient but movement_type is empty")
    return errors


def _q(val):
    return '"' + val.replace("\\", "\\\\").replace('"', '\\"') + '"'

def _opt_str(val):
    v = (val or "").strip()
    return "None" if not v else _q(v)

def _opt_numeric(val, cast):
    v = (val or "").strip()
    if not v: return "None"
    try: return str(cast(v))
    except ValueError: return "None"

def _opt_bool(val):
    v = (val or "").strip().upper()
    if v in ("TRUE","1","YES"): return "True"
    if v in ("FALSE","0","NO"): return "False"
    return "None"

HEADER = '''\
# extracted_enemy_locations.py
# AUTO-GENERATED by tools/generate_enemies.py — DO NOT EDIT MANUALLY.
# Source of truth: data/enemy_locations.csv
# Re-generate:     python tools/generate_enemies.py

from __future__ import annotations
from typing import NamedTuple, Optional


class EnemyLocation(NamedTuple):
    """
    One enemy spawn slot in Shadow Man Remastered.

    Patcher fields:
        level_id, source_file, offset

    Display fields:
        friendly_name, object, category

    Shuffle fields:
        context_group  : "deadside" | "deadside_interior" | "liveside" | "asylum" | "any"
                         Empty for enemy_locked. In contextual mode, enemies shuffle
                         globally within their context_group.
        movement_type  : "ground" | "flying" | "swimming"
                         Always respected — enemies only shuffle with same movement type.
                         Empty for enemy_locked records.

    Tracking fields (ignored by shuffle logic):
        save_idx, is_tracked, is_verified, zone, x, y, z, notes
    """
    level_id:      str
    source_file:   str
    offset:        int
    friendly_name: Optional[str]
    object:        str
    category:      str
    context_group: Optional[str]
    movement_type: Optional[str]
    level_region:  Optional[str]
    sub_region:    Optional[str]
    gate_expr:     Optional[str]
    save_idx:      Optional[int]
    is_tracked:    Optional[bool]
    is_verified:   Optional[bool]
    zone:          Optional[str]
    x:             Optional[float]
    y:             Optional[float]
    z:             Optional[float]
    notes:         Optional[str]

    @property
    def loc_key(self) -> str:
        return f"{self.level_id}:{self.source_file}:0x{self.offset:04X}"


ENEMY_LOCATIONS: list[EnemyLocation] = [
'''

FOOTER = '''\
]

# ── Derived lookups ───────────────────────────────────────────────────────────

ENEMY_TABLE: dict[str, EnemyLocation] = {
    loc.loc_key: loc for loc in ENEMY_LOCATIONS
}

ENEMIES_BY_LEVEL: dict[str, list[EnemyLocation]] = {}
for _loc in ENEMY_LOCATIONS:
    ENEMIES_BY_LEVEL.setdefault(_loc.level_id, []).append(_loc)

SHUFFLEABLE_BY_LEVEL: dict[str, list[EnemyLocation]] = {}
for _loc in ENEMY_LOCATIONS:
    if _loc.category == "enemy":
        SHUFFLEABLE_BY_LEVEL.setdefault(_loc.level_id, []).append(_loc)

# (context_group, movement_type) -> list of shuffleable slots
# Used by contextual mode — shuffle within group AND movement type.
SLOTS_BY_CONTEXT: dict[tuple[str, str], list[EnemyLocation]] = {}
for _loc in ENEMY_LOCATIONS:
    if _loc.category == "enemy" and _loc.context_group and _loc.movement_type:
        _key = (_loc.context_group, _loc.movement_type)
        SLOTS_BY_CONTEXT.setdefault(_key, []).append(_loc)

# movement_type -> list of shuffleable slots
# Used by full mode — shuffle globally within movement type only.
SLOTS_BY_MOVEMENT: dict[str, list[EnemyLocation]] = {}
for _loc in ENEMY_LOCATIONS:
    if _loc.category == "enemy" and _loc.movement_type:
        SLOTS_BY_MOVEMENT.setdefault(_loc.movement_type, []).append(_loc)
        
# movement_type -> list of shuffleable ambient slots (full mode)
AMBIENT_BY_MOVEMENT: dict[str, list[EnemyLocation]] = {}
for _loc in ENEMY_LOCATIONS:
    if _loc.category == "ambient" and _loc.movement_type:
        AMBIENT_BY_MOVEMENT.setdefault(_loc.movement_type, []).append(_loc)

# (context_group, movement_type) -> list of ambient slots (contextual mode)
AMBIENT_BY_CONTEXT: dict[tuple[str, str], list[EnemyLocation]] = {}
for _loc in ENEMY_LOCATIONS:
    if _loc.category == "ambient" and _loc.context_group and _loc.movement_type:
        AMBIENT_BY_CONTEXT.setdefault((_loc.context_group, _loc.movement_type), []).append(_loc)

# All ambient slots in one flat list (global mode — no bucketing)
AMBIENT_ALL: list[EnemyLocation] = [
    _loc for _loc in ENEMY_LOCATIONS if _loc.category == "ambient"
]

# (level_id, object) -> list of boss records
# Used by boss_randomizer to patch ALL records for a given boss in a level
# (primary spawn + encounter phases) when shuffling bosses between levels.
BOSS_BY_LEVEL_RSC: dict[tuple[str, str], list[EnemyLocation]] = {}
for _loc in ENEMY_LOCATIONS:
    if _loc.category == "boss":
        BOSS_BY_LEVEL_RSC.setdefault((_loc.level_id, _loc.object), []).append(_loc)
'''


def generate(rows):
    lines = [HEADER]
    for row in rows:
        lid  = row["level_id"].strip()
        sf   = row["source_file"].strip()
        off  = parse_offset(row["offset"].strip())
        obj  = row["object"].strip()
        cat  = row["category"].strip()
        cg   = row["context_group"].strip()
        mt   = row["movement_type"].strip()
        lr = row.get("level_region", "").strip()
        sr = row.get("sub_region", "").strip()
        try:
            ge = parse_gate_expr(sr) if sr else None
        except ValueError as e:
            raise ValueError(f"Row {lid}:{sf}: bad sub_region '{sr}': {e}")

        rsc_body = obj
        for prefix in ("RSC_A_","RSC_BAD_","RSC_D_","RSC_X_","RSC_T_","RSC_"):
            if rsc_body.startswith(prefix):
                rsc_body = rsc_body[len(prefix):]
                break
        friendly = rsc_body.replace("_"," ").title()

        lines.append(
            f"    EnemyLocation("
            f"{_q(lid)}, {_q(sf)}, 0x{off:04X}, "
            f"{_q(friendly)}, {_q(obj)}, {_q(cat)}, "
            f"{'None' if not cg else _q(cg)}, "
            f"{'None' if not mt else _q(mt)}, "
            f"{'None' if not lr else _q(lr)}, "
            f"{'None' if not sr else _q(sr)}, "
            f"{'None' if ge is None else _q(ge)}, "
            f"{_opt_numeric(row.get('save_idx',''), int)}, "
            f"{_opt_bool(row.get('is_tracked',''))}, "
            f"{_opt_bool(row.get('is_verified',''))}, "
            f"{_opt_str(row.get('zone',''))}, "
            f"{_opt_numeric(row.get('x',''), float)}, "
            f"{_opt_numeric(row.get('y',''), float)}, "
            f"{_opt_numeric(row.get('z',''), float)}, "
            f"{_opt_str(row.get('notes',''))}),\n"
        )
    lines.append(FOOTER)
    return "".join(lines)


def main():
    if not CSV_PATH.exists():
        print(f"ERROR: CSV not found at {CSV_PATH}", file=sys.stderr)
        sys.exit(1)

    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    missing = REQUIRED_COLUMNS - set(reader.fieldnames or [])
    if missing:
        print(f"ERROR: CSV missing columns: {sorted(missing)}", file=sys.stderr)
        sys.exit(1)

    errors = validate(rows)
    if errors:
        print(f"Found {len(errors)} error(s):", file=sys.stderr)
        for e in errors: print(f"  {e}", file=sys.stderr)
        sys.exit(1)

    OUT_PATH.write_text(generate(rows), encoding="utf-8")
    print(f"✓ Generated {len(rows)} enemy locations → {OUT_PATH.name}")

    by_cat     = Counter(r['category'] for r in rows)
    by_mt      = Counter(r['movement_type'] for r in rows if r['category'] == 'enemy')
    by_cg      = Counter(r['context_group'] for r in rows if r['category'] == 'enemy')
    amb_by_mt  = Counter(r['movement_type'] for r in rows if r['category'] == 'ambient')
    amb_by_cg  = Counter(r['context_group'] for r in rows if r['category'] == 'ambient')
    boss_by_cg = Counter(r['context_group'] for r in rows if r['category'] == 'boss')

    print(f"\n  enemy={by_cat['enemy']}  enemy_locked={by_cat['enemy_locked']}"
          f"  ambient={by_cat['ambient']}  ambient_locked={by_cat['ambient_locked']}"
          f"  boss={by_cat['boss']}  boss_locked={by_cat['boss_locked']}")
    print("\nShuffleable by movement_type:")
    for mt, n in sorted(by_mt.items()):
        print(f"  {mt or '(empty)':<12} {n}")
    print("\nShuffleable by context_group:")
    for cg, n in sorted(by_cg.items()):
        print(f"  {cg or '(empty)':<25} {n}")
    if by_cat['ambient']:
        print("\nAmbient by movement_type:")
        for mt, n in sorted(amb_by_mt.items()):
            print(f"  {mt or '(empty)':<12} {n}")
        print("\nAmbient by context_group:")
        for cg, n in sorted(amb_by_cg.items()):
            print(f"  {cg or '(empty)':<25} {n}")
    if by_cat['boss']:
        print("\nBoss by context_group:")
        for cg, n in sorted(boss_by_cg.items()):
            print(f"  {cg or '(empty)':<25} {n}")


if __name__ == "__main__":
    main()
